// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xmwnigverszyrvxkhseu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhtd25pZ3ZlcnN6eXJ2eGtoc2V1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4OTQxMDcsImV4cCI6MjA4NzQ3MDEwN30.nQx8-A_amXtsOtpxFGFphGu40bqznMXh1h62ADIWmfE";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);